//
// UIColor+Copic.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
// Created by Mihaela Mihaljević Jakić
// Color codes source: http://blog.paigeedraw.com/2012/07/copic-marker-color-rgb-hex-conversion.html
//
//

#import "UIColor+Copic.h"

@implementation UIColor (Copic)

+(UIColor *)copic_0_Color 
{
	return [UIColor colorWithRed:255/255.0 green:255/255.0 blue:255/255.0 alpha:255/255.0];
};

+(UIColor *)copic_100_Color 
{
	return [UIColor colorWithRed:49/255.0 green:43/255.0 blue:43/255.0 alpha:255/255.0];
};

+(UIColor *)copic_110_Color 
{
	return [UIColor colorWithRed:3/255.0 green:7/255.0 blue:8/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b00_Color 
{
	return [UIColor colorWithRed:221/255.0 green:240/255.0 blue:244/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b000_Color 
{
	return [UIColor colorWithRed:230/255.0 green:244/255.0 blue:245/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b0000_Color 
{
	return [UIColor colorWithRed:240/255.0 green:249/255.0 blue:254/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b01_Color 
{
	return [UIColor colorWithRed:214/255.0 green:238/255.0 blue:242/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b02_Color 
{
	return [UIColor colorWithRed:179/255.0 green:227/255.0 blue:241/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b04_Color 
{
	return [UIColor colorWithRed:115/255.0 green:207/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b05_Color 
{
	return [UIColor colorWithRed:64/255.0 green:197/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b06_Color 
{
	return [UIColor colorWithRed:0/255.0 green:179/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b12_Color 
{
	return [UIColor colorWithRed:200/255.0 green:230/255.0 blue:240/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b14_Color 
{
	return [UIColor colorWithRed:113/255.0 green:207/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b16_Color 
{
	return [UIColor colorWithRed:0/255.0 green:188/255.0 blue:234/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b18_Color 
{
	return [UIColor colorWithRed:29/255.0 green:138/255.0 blue:203/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b21_Color 
{
	return [UIColor colorWithRed:219/255.0 green:237/255.0 blue:249/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b23_Color 
{
	return [UIColor colorWithRed:146/255.0 green:194/255.0 blue:232/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b24_Color 
{
	return [UIColor colorWithRed:138/255.0 green:206/255.0 blue:243/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b26_Color 
{
	return [UIColor colorWithRed:101/255.0 green:179/255.0 blue:227/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b28_Color 
{
	return [UIColor colorWithRed:25/255.0 green:109/255.0 blue:182/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b29_Color 
{
	return [UIColor colorWithRed:1/255.0 green:119/255.0 blue:193/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b32_Color 
{
	return [UIColor colorWithRed:226/255.0 green:239/255.0 blue:247/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b34_Color 
{
	return [UIColor colorWithRed:130/255.0 green:195/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b37_Color 
{
	return [UIColor colorWithRed:21/255.0 green:111/255.0 blue:164/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b39_Color 
{
	return [UIColor colorWithRed:43/255.0 green:100/255.0 blue:169/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b41_Color 
{
	return [UIColor colorWithRed:226/255.0 green:240/255.0 blue:251/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b45_Color 
{
	return [UIColor colorWithRed:117/255.0 green:192/255.0 blue:234/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b52_Color 
{
	return [UIColor colorWithRed:173/255.0 green:205/255.0 blue:220/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b60_Color 
{
	return [UIColor colorWithRed:218/255.0 green:225/255.0 blue:243/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b63_Color 
{
	return [UIColor colorWithRed:167/255.0 green:187/255.0 blue:224/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b66_Color 
{
	return [UIColor colorWithRed:104/255.0 green:136/255.0 blue:197/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b69_Color 
{
	return [UIColor colorWithRed:33/255.0 green:101/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b79_Color 
{
	return [UIColor colorWithRed:59/255.0 green:71/255.0 blue:157/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b91_Color 
{
	return [UIColor colorWithRed:213/255.0 green:226/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b93_Color 
{
	return [UIColor colorWithRed:149/255.0 green:193/255.0 blue:218/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b95_Color 
{
	return [UIColor colorWithRed:96/255.0 green:197/255.0 blue:207/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b97_Color 
{
	return [UIColor colorWithRed:69/255.0 green:122/255.0 blue:154/255.0 alpha:255/255.0];
};

+(UIColor *)copic_b99_Color 
{
	return [UIColor colorWithRed:15/255.0 green:84/255.0 blue:126/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg000_Color 
{
	return [UIColor colorWithRed:229/255.0 green:244/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg0000_Color 
{
	return [UIColor colorWithRed:239/255.0 green:248/255.0 blue:243/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg01_Color 
{
	return [UIColor colorWithRed:199/255.0 green:230/255.0 blue:250/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg02_Color 
{
	return [UIColor colorWithRed:198/255.0 green:232/255.0 blue:234/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg05_Color 
{
	return [UIColor colorWithRed:29/255.0 green:184/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg07_Color 
{
	return [UIColor colorWithRed:29/255.0 green:184/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg09_Color 
{
	return [UIColor colorWithRed:220/255.0 green:240/255.0 blue:239/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg10_Color 
{
	return [UIColor colorWithRed:220/255.0 green:240/255.0 blue:239/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg11_Color 
{
	return [UIColor colorWithRed:206/255.0 green:235/255.0 blue:241/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg13_Color 
{
	return [UIColor colorWithRed:196/255.0 green:231/255.0 blue:233/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg15_Color 
{
	return [UIColor colorWithRed:160/255.0 green:217/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg18_Color 
{
	return [UIColor colorWithRed:55/255.0 green:192/255.0 blue:176/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg23_Color 
{
	return [UIColor colorWithRed:189/255.0 green:229/255.0 blue:221/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg32_Color 
{
	return [UIColor colorWithRed:188/255.0 green:226/255.0 blue:215/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg34_Color 
{
	return [UIColor colorWithRed:163/255.0 green:218/255.0 blue:215/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg45_Color 
{
	return [UIColor colorWithRed:175/255.0 green:223/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg49_Color 
{
	return [UIColor colorWithRed:0/255.0 green:182/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg53_Color 
{
	return [UIColor colorWithRed:172/255.0 green:207/255.0 blue:209/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg57_Color 
{
	return [UIColor colorWithRed:100/255.0 green:190/255.0 blue:190/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg70_Color 
{
	return [UIColor colorWithRed:218/255.0 green:236/255.0 blue:238/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg72_Color 
{
	return [UIColor colorWithRed:116/255.0 green:184/255.0 blue:187/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg75_Color 
{
	return [UIColor colorWithRed:89/255.0 green:145/255.0 blue:142/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg78_Color 
{
	return [UIColor colorWithRed:73/255.0 green:112/255.0 blue:107/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg90_Color 
{
	return [UIColor colorWithRed:186/255.0 green:193/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg93_Color 
{
	return [UIColor colorWithRed:186/255.0 green:193/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg96_Color 
{
	return [UIColor colorWithRed:129/255.0 green:162/255.0 blue:145/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bg99_Color 
{
	return [UIColor colorWithRed:110/255.0 green:155/255.0 blue:135/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv00_Color 
{
	return [UIColor colorWithRed:224/255.0 green:220/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv000_Color 
{
	return [UIColor colorWithRed:234/255.0 green:231/255.0 blue:242/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv0000_Color 
{
	return [UIColor colorWithRed:234/255.0 green:231/255.0 blue:242/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv01_Color 
{
	return [UIColor colorWithRed:196/255.0 green:201/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv02_Color 
{
	return [UIColor colorWithRed:170/255.0 green:184/255.0 blue:219/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv04_Color 
{
	return [UIColor colorWithRed:124/255.0 green:151/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv08_Color 
{
	return [UIColor colorWithRed:234/255.0 green:231/255.0 blue:242/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv11_Color 
{
	return [UIColor colorWithRed:212/255.0 green:210/255.0 blue:232/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv13_Color 
{
	return [UIColor colorWithRed:132/255.0 green:145/255.0 blue:200/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv17_Color 
{
	return [UIColor colorWithRed:110/255.0 green:132/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv20_Color 
{
	return [UIColor colorWithRed:207/255.0 green:219/255.0 blue:241/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv23_Color 
{
	return [UIColor colorWithRed:177/255.0 green:192/255.0 blue:221/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv25_Color 
{
	return [UIColor colorWithRed:129/255.0 green:132/255.0 blue:167/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv29_Color 
{
	return [UIColor colorWithRed:56/255.0 green:69/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv31_Color 
{
	return [UIColor colorWithRed:234/255.0 green:231/255.0 blue:242/255.0 alpha:255/255.0];
};

+(UIColor *)copic_bv34_Color 
{
	return [UIColor colorWithRed:159/255.0 green:167/255.0 blue:188/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c0_Color 
{
	return [UIColor colorWithRed:224/255.0 green:231/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c00_Color 
{
	return [UIColor colorWithRed:224/255.0 green:231/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c1_Color 
{
	return [UIColor colorWithRed:218/255.0 green:227/255.0 blue:232/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c10_Color 
{
	return [UIColor colorWithRed:32/255.0 green:43/255.0 blue:49/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c2_Color 
{
	return [UIColor colorWithRed:204/255.0 green:215/255.0 blue:221/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c3_Color 
{
	return [UIColor colorWithRed:193/255.0 green:204/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c4_Color 
{
	return [UIColor colorWithRed:146/255.0 green:160/255.0 blue:171/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c5_Color 
{
	return [UIColor colorWithRed:146/255.0 green:160/255.0 blue:171/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c6_Color 
{
	return [UIColor colorWithRed:99/255.0 green:112/255.0 blue:121/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c7_Color 
{
	return [UIColor colorWithRed:99/255.0 green:112/255.0 blue:121/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c8_Color 
{
	return [UIColor colorWithRed:83/255.0 green:93/255.0 blue:102/255.0 alpha:255/255.0];
};

+(UIColor *)copic_c9_Color 
{
	return [UIColor colorWithRed:60/255.0 green:71/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e00_Color 
{
	return [UIColor colorWithRed:253/255.0 green:243/255.0 blue:234/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e000_Color 
{
	return [UIColor colorWithRed:254/255.0 green:245/255.0 blue:238/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e0000_Color 
{
	return [UIColor colorWithRed:255/255.0 green:250/255.0 blue:244/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e01_Color 
{
	return [UIColor colorWithRed:255/255.0 green:238/255.0 blue:228/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e02_Color 
{
	return [UIColor colorWithRed:254/255.0 green:236/255.0 blue:224/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e04_Color 
{
	return [UIColor colorWithRed:228/255.0 green:188/255.0 blue:196/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e07_Color 
{
	return [UIColor colorWithRed:204/255.0 green:129/255.0 blue:106/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e08_Color 
{
	return [UIColor colorWithRed:202/255.0 green:101/255.0 blue:83/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e09_Color 
{
	return [UIColor colorWithRed:217/255.0 green:106/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e11_Color 
{
	return [UIColor colorWithRed:254/255.0 green:233/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e13_Color 
{
	return [UIColor colorWithRed:233/255.0 green:197/255.0 blue:175/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e15_Color 
{
	return [UIColor colorWithRed:251/255.0 green:187/255.0 blue:141/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e17_Color 
{
	return [UIColor colorWithRed:184/255.0 green:95/255.0 blue:87/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e18_Color 
{
	return [UIColor colorWithRed:136/255.0 green:83/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e19_Color 
{
	return [UIColor colorWithRed:196/255.0 green:82/255.0 blue:56/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e21_Color 
{
	return [UIColor colorWithRed:253/255.0 green:226/255.0 blue:199/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e23_Color 
{
	return [UIColor colorWithRed:236/255.0 green:202/255.0 blue:177/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e25_Color 
{
	return [UIColor colorWithRed:210/255.0 green:164/255.0 blue:130/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e27_Color 
{
	return [UIColor colorWithRed:153/255.0 green:118/255.0 blue:99/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e29_Color 
{
	return [UIColor colorWithRed:136/255.0 green:70/255.0 blue:54/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e30_Color 
{
	return [UIColor colorWithRed:247/255.0 green:240/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e31_Color 
{
	return [UIColor colorWithRed:242/255.0 green:230/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e33_Color 
{
	return [UIColor colorWithRed:243/255.0 green:210/255.0 blue:177/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e34_Color 
{
	return [UIColor colorWithRed:240/255.0 green:202/255.0 blue:166/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e35_Color 
{
	return [UIColor colorWithRed:230/255.0 green:195/255.0 blue:163/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e37_Color 
{
	return [UIColor colorWithRed:204/255.0 green:145/255.0 blue:89/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e39_Color 
{
	return [UIColor colorWithRed:197/255.0 green:116/255.0 blue:63/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e40_Color 
{
	return [UIColor colorWithRed:242/255.0 green:232/255.0 blue:220/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e41_Color 
{
	return [UIColor colorWithRed:254/255.0 green:241/255.0 blue:225/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e42_Color 
{
	return [UIColor colorWithRed:243/255.0 green:234/255.0 blue:217/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e43_Color 
{
	return [UIColor colorWithRed:232/255.0 green:218/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e44_Color 
{
	return [UIColor colorWithRed:138/255.0 green:110/255.0 blue:89/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e47_Color 
{
	return [UIColor colorWithRed:138/255.0 green:110/255.0 blue:89/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e49_Color 
{
	return [UIColor colorWithRed:99/255.0 green:76/255.0 blue:60/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e50_Color 
{
	return [UIColor colorWithRed:244/255.0 green:235/255.0 blue:240/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e51_Color 
{
	return [UIColor colorWithRed:254/255.0 green:236/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e53_Color 
{
	return [UIColor colorWithRed:241/255.0 green:223/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e55_Color 
{
	return [UIColor colorWithRed:241/255.0 green:223/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e57_Color 
{
	return [UIColor colorWithRed:177/255.0 green:133/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e59_Color 
{
	return [UIColor colorWithRed:154/255.0 green:127/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e70_Color 
{
	return [UIColor colorWithRed:239/255.0 green:234/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e71_Color 
{
	return [UIColor colorWithRed:161/255.0 green:132/255.0 blue:124/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e74_Color 
{
	return [UIColor colorWithRed:161/255.0 green:132/255.0 blue:124/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e77_Color 
{
	return [UIColor colorWithRed:127/255.0 green:96/255.0 blue:78/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e79_Color 
{
	return [UIColor colorWithRed:74/255.0 green:44/255.0 blue:34/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e81_Color 
{
	return [UIColor colorWithRed:240/255.0 green:230/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e84_Color 
{
	return [UIColor colorWithRed:174/255.0 green:159/255.0 blue:128/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e87_Color 
{
	return [UIColor colorWithRed:111/255.0 green:96/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e89_Color 
{
	return [UIColor colorWithRed:90/255.0 green:73/255.0 blue:57/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e93_Color 
{
	return [UIColor colorWithRed:254/255.0 green:210/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e95_Color 
{
	return [UIColor colorWithRed:252/255.0 green:188/255.0 blue:126/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e97_Color 
{
	return [UIColor colorWithRed:180/255.0 green:96/255.0 blue:52/255.0 alpha:255/255.0];
};

+(UIColor *)copic_e99_Color 
{
	return [UIColor colorWithRed:180/255.0 green:96/255.0 blue:52/255.0 alpha:255/255.0];
};

+(UIColor *)copic_frv1_Color 
{
	return [UIColor colorWithRed:245/255.0 green:163/255.0 blue:199/255.0 alpha:255/255.0];
};

+(UIColor *)copic_fv2_Color 
{
	return [UIColor colorWithRed:127/255.0 green:116/255.0 blue:182/255.0 alpha:255/255.0];
};

+(UIColor *)copic_fy1_Color 
{
	return [UIColor colorWithRed:255/255.0 green:246/255.0 blue:151/255.0 alpha:255/255.0];
};

+(UIColor *)copic_fyr1_Color 
{
	return [UIColor colorWithRed:254/255.0 green:204/255.0 blue:153/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g00_Color 
{
	return [UIColor colorWithRed:227/255.0 green:242/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g000_Color 
{
	return [UIColor colorWithRed:234/255.0 green:245/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g0000_Color 
{
	return [UIColor colorWithRed:241/255.0 green:247/255.0 blue:243/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g02_Color 
{
	return [UIColor colorWithRed:207/255.0 green:232/255.0 blue:211/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g03_Color 
{
	return [UIColor colorWithRed:182/255.0 green:218/255.0 blue:156/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g05_Color 
{
	return [UIColor colorWithRed:105/255.0 green:192/255.0 blue:123/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g07_Color 
{
	return [UIColor colorWithRed:123/255.0 green:197/255.0 blue:118/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g09_Color 
{
	return [UIColor colorWithRed:122/255.0 green:196/255.0 blue:101/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g12_Color 
{
	return [UIColor colorWithRed:210/255.0 green:232/255.0 blue:196/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g14_Color 
{
	return [UIColor colorWithRed:151/255.0 green:207/255.0 blue:144/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g16_Color 
{
	return [UIColor colorWithRed:96/255.0 green:193/255.0 blue:152/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g17_Color 
{
	return [UIColor colorWithRed:20/255.0 green:179/255.0 blue:125/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g19_Color 
{
	return [UIColor colorWithRed:45/255.0 green:185/255.0 blue:138/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g20_Color 
{
	return [UIColor colorWithRed:237/255.0 green:246/255.0 blue:219/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g21_Color 
{
	return [UIColor colorWithRed:196/255.0 green:228/255.0 blue:205/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g24_Color 
{
	return [UIColor colorWithRed:195/255.0 green:224/255.0 blue:180/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g28_Color 
{
	return [UIColor colorWithRed:17/255.0 green:148/255.0 blue:98/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g29_Color 
{
	return [UIColor colorWithRed:25/255.0 green:124/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g40_Color 
{
	return [UIColor colorWithRed:228/255.0 green:241/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g43_Color 
{
	return [UIColor colorWithRed:215/255.0 green:231/255.0 blue:168/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g46_Color 
{
	return [UIColor colorWithRed:88/255.0 green:159/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g82_Color 
{
	return [UIColor colorWithRed:204/255.0 green:218/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g85_Color 
{
	return [UIColor colorWithRed:157/255.0 green:195/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g94_Color 
{
	return [UIColor colorWithRed:152/255.0 green:167/255.0 blue:134/255.0 alpha:255/255.0];
};

+(UIColor *)copic_g99_Color 
{
	return [UIColor colorWithRed:95/255.0 green:126/255.0 blue:58/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n0_Color 
{
	return [UIColor colorWithRed:236/255.0 green:238/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n1_Color 
{
	return [UIColor colorWithRed:226/255.0 green:227/255.0 blue:229/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n10_Color 
{
	return [UIColor colorWithRed:49/255.0 green:47/255.0 blue:48/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n2_Color 
{
	return [UIColor colorWithRed:218/255.0 green:219/255.0 blue:221/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n3_Color 
{
	return [UIColor colorWithRed:209/255.0 green:210/255.0 blue:212/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n4_Color 
{
	return [UIColor colorWithRed:188/255.0 green:189/255.0 blue:193/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n5_Color 
{
	return [UIColor colorWithRed:168/255.0 green:169/255.0 blue:173/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n6_Color 
{
	return [UIColor colorWithRed:148/255.0 green:149/255.0 blue:153/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n7_Color 
{
	return [UIColor colorWithRed:119/255.0 green:120/255.0 blue:124/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n8_Color 
{
	return [UIColor colorWithRed:99/255.0 green:100/255.0 blue:102/255.0 alpha:255/255.0];
};

+(UIColor *)copic_n9_Color 
{
	return [UIColor colorWithRed:76/255.0 green:77/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r00_Color 
{
	return [UIColor colorWithRed:254/255.0 green:234/255.0 blue:225/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r000_Color 
{
	return [UIColor colorWithRed:254/255.0 green:240/255.0 blue:231/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r0000_Color 
{
	return [UIColor colorWithRed:254/255.0 green:243/255.0 blue:239/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r01_Color 
{
	return [UIColor colorWithRed:253/255.0 green:224/255.0 blue:216/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r02_Color 
{
	return [UIColor colorWithRed:253/255.0 green:211/255.0 blue:199/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r05_Color 
{
	return [UIColor colorWithRed:246/255.0 green:145/255.0 blue:123/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r07_Color 
{
	return [UIColor colorWithRed:242/255.0 green:111/255.0 blue:57/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r08_Color 
{
	return [UIColor colorWithRed:242/255.0 green:103/255.0 blue:84/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r11_Color 
{
	return [UIColor colorWithRed:253/255.0 green:225/255.0 blue:213/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r12_Color 
{
	return [UIColor colorWithRed:252/255.0 green:211/255.0 blue:193/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r14_Color 
{
	return [UIColor colorWithRed:245/255.0 green:155/255.0 blue:146/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r17_Color 
{
	return [UIColor colorWithRed:244/255.0 green:132/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r20_Color 
{
	return [UIColor colorWithRed:252/255.0 green:215/255.0 blue:207/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r21_Color 
{
	return [UIColor colorWithRed:250/255.0 green:193/255.0 blue:182/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r22_Color 
{
	return [UIColor colorWithRed:248/255.0 green:183/255.0 blue:177/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r24_Color 
{
	return [UIColor colorWithRed:242/255.0 green:117/255.0 blue:121/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r27_Color 
{
	return [UIColor colorWithRed:241/255.0 green:80/255.0 blue:98/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r29_Color 
{
	return [UIColor colorWithRed:237/255.0 green:23/255.0 blue:75/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r30_Color 
{
	return [UIColor colorWithRed:252/255.0 green:227/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r32_Color 
{
	return [UIColor colorWithRed:250/255.0 green:193/255.0 blue:186/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r35_Color 
{
	return [UIColor colorWithRed:242/255.0 green:113/255.0 blue:133/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r37_Color 
{
	return [UIColor colorWithRed:232/255.0 green:108/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r39_Color 
{
	return [UIColor colorWithRed:203/255.0 green:72/255.0 blue:122/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r43_Color 
{
	return [UIColor colorWithRed:238/255.0 green:132/255.0 blue:142/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r46_Color 
{
	return [UIColor colorWithRed:224/255.0 green:77/255.0 blue:105/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r56_Color 
{
	return [UIColor colorWithRed:210/255.0 green:124/255.0 blue:149/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r59_Color 
{
	return [UIColor colorWithRed:183/255.0 green:79/255.0 blue:112/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r81_Color 
{
	return [UIColor colorWithRed:241/255.0 green:200/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r83_Color 
{
	return [UIColor colorWithRed:241/255.0 green:156/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r85_Color 
{
	return [UIColor colorWithRed:211/255.0 green:106/255.0 blue:147/255.0 alpha:255/255.0];
};

+(UIColor *)copic_r89_Color 
{
	return [UIColor colorWithRed:125/255.0 green:43/255.0 blue:66/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv00_Color 
{
	return [UIColor colorWithRed:241/255.0 green:218/255.0 blue:234/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv000_Color 
{
	return [UIColor colorWithRed:244/255.0 green:226/255.0 blue:238/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv0000_Color 
{
	return [UIColor colorWithRed:242/255.0 green:234/255.0 blue:245/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv02_Color 
{
	return [UIColor colorWithRed:250/255.0 green:213/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv04_Color 
{
	return [UIColor colorWithRed:246/255.0 green:163/255.0 blue:191/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv06_Color 
{
	return [UIColor colorWithRed:243/255.0 green:134/255.0 blue:175/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv10_Color 
{
	return [UIColor colorWithRed:253/255.0 green:236/255.0 blue:244/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv11_Color 
{
	return [UIColor colorWithRed:251/255.0 green:214/255.0 blue:221/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv13_Color 
{
	return [UIColor colorWithRed:249/255.0 green:201/255.0 blue:215/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv14_Color 
{
	return [UIColor colorWithRed:244/255.0 green:149/255.0 blue:183/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv17_Color 
{
	return [UIColor colorWithRed:219/255.0 green:126/255.0 blue:179/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv19_Color 
{
	return [UIColor colorWithRed:210/255.0 green:104/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv21_Color 
{
	return [UIColor colorWithRed:253/255.0 green:232/255.0 blue:231/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv23_Color 
{
	return [UIColor colorWithRed:248/255.0 green:186/255.0 blue:201/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv25_Color 
{
	return [UIColor colorWithRed:244/255.0 green:147/255.0 blue:190/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv29_Color 
{
	return [UIColor colorWithRed:239/255.0 green:72/255.0 blue:128/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv32_Color 
{
	return [UIColor colorWithRed:250/255.0 green:211/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv34_Color 
{
	return [UIColor colorWithRed:249/255.0 green:175/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv42_Color 
{
	return [UIColor colorWithRed:248/255.0 green:187/255.0 blue:182/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv52_Color 
{
	return [UIColor colorWithRed:249/255.0 green:202/255.0 blue:222/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv55_Color 
{
	return [UIColor colorWithRed:233/255.0 green:165/255.0 blue:202/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv63_Color 
{
	return [UIColor colorWithRed:208/255.0 green:157/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv66_Color 
{
	return [UIColor colorWithRed:184/255.0 green:106/255.0 blue:132/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv69_Color 
{
	return [UIColor colorWithRed:139/255.0 green:87/255.0 blue:110/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv95_Color 
{
	return [UIColor colorWithRed:182/255.0 green:132/255.0 blue:161/255.0 alpha:255/255.0];
};

+(UIColor *)copic_rv99_Color 
{
	return [UIColor colorWithRed:90/255.0 green:72/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t0_Color 
{
	return [UIColor colorWithRed:236/255.0 green:238/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t1_Color 
{
	return [UIColor colorWithRed:234/255.0 green:234/255.0 blue:232/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t10_Color 
{
	return [UIColor colorWithRed:50/255.0 green:46/255.0 blue:45/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t2_Color 
{
	return [UIColor colorWithRed:224/255.0 green:224/255.0 blue:222/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t3_Color 
{
	return [UIColor colorWithRed:209/255.0 green:210/255.0 blue:204/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t4_Color 
{
	return [UIColor colorWithRed:188/255.0 green:187/255.0 blue:185/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t5_Color 
{
	return [UIColor colorWithRed:168/255.0 green:167/255.0 blue:163/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t6_Color 
{
	return [UIColor colorWithRed:148/255.0 green:149/255.0 blue:144/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t7_Color 
{
	return [UIColor colorWithRed:119/255.0 green:118/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t8_Color 
{
	return [UIColor colorWithRed:99/255.0 green:100/255.0 blue:95/255.0 alpha:255/255.0];
};

+(UIColor *)copic_t9_Color 
{
	return [UIColor colorWithRed:76/255.0 green:75/255.0 blue:73/255.0 alpha:255/255.0];
};

+(UIColor *)copic_tg13_Color 
{
	return [UIColor colorWithRed:212/255.0 green:229/255.0 blue:159/255.0 alpha:255/255.0];
};

+(UIColor *)copic_tr000_Color 
{
	return [UIColor colorWithRed:254/255.0 green:236/255.0 blue:216/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v000_Color 
{
	return [UIColor colorWithRed:233/255.0 green:229/255.0 blue:243/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v0000_Color 
{
	return [UIColor colorWithRed:240/255.0 green:237/255.0 blue:246/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v01_Color 
{
	return [UIColor colorWithRed:228/255.0 green:193/255.0 blue:217/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v04_Color 
{
	return [UIColor colorWithRed:230/255.0 green:170/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v05_Color 
{
	return [UIColor colorWithRed:226/255.0 green:166/255.0 blue:202/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v06_Color 
{
	return [UIColor colorWithRed:206/255.0 green:149/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v09_Color 
{
	return [UIColor colorWithRed:135/255.0 green:84/255.0 blue:161/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v12_Color 
{
	return [UIColor colorWithRed:238/255.0 green:215/255.0 blue:233/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v15_Color 
{
	return [UIColor colorWithRed:211/255.0 green:166/255.0 blue:205/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v17_Color 
{
	return [UIColor colorWithRed:160/255.0 green:146/255.0 blue:199/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v20_Color 
{
	return [UIColor colorWithRed:226/255.0 green:224/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v22_Color 
{
	return [UIColor colorWithRed:178/255.0 green:177/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v25_Color 
{
	return [UIColor colorWithRed:133/255.0 green:127/255.0 blue:173/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v28_Color 
{
	return [UIColor colorWithRed:107/255.0 green:102/255.0 blue:142/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v91_Color 
{
	return [UIColor colorWithRed:232/255.0 green:196/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v93_Color 
{
	return [UIColor colorWithRed:229/255.0 green:193/255.0 blue:219/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v95_Color 
{
	return [UIColor colorWithRed:183/255.0 green:124/255.0 blue:168/255.0 alpha:255/255.0];
};

+(UIColor *)copic_v99_Color 
{
	return [UIColor colorWithRed:82/255.0 green:67/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w0_Color 
{
	return [UIColor colorWithRed:236/255.0 green:236/255.0 blue:228/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w00_Color 
{
	return [UIColor colorWithRed:243/255.0 green:243/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w1_Color 
{
	return [UIColor colorWithRed:231/255.0 green:231/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w10_Color 
{
	return [UIColor colorWithRed:48/255.0 green:47/255.0 blue:43/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w2_Color 
{
	return [UIColor colorWithRed:221/255.0 green:221/255.0 blue:213/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w3_Color 
{
	return [UIColor colorWithRed:210/255.0 green:210/255.0 blue:202/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w4_Color 
{
	return [UIColor colorWithRed:188/255.0 green:189/255.0 blue:183/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w5_Color 
{
	return [UIColor colorWithRed:168/255.0 green:169/255.0 blue:164/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w6_Color 
{
	return [UIColor colorWithRed:148/255.0 green:149/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w7_Color 
{
	return [UIColor colorWithRed:119/255.0 green:120/255.0 blue:115/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w8_Color 
{
	return [UIColor colorWithRed:99/255.0 green:100/255.0 blue:95/255.0 alpha:255/255.0];
};

+(UIColor *)copic_w9_Color 
{
	return [UIColor colorWithRed:76/255.0 green:77/255.0 blue:72/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y00_Color 
{
	return [UIColor colorWithRed:254/255.0 green:253/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y000_Color 
{
	return [UIColor colorWithRed:255/255.0 green:252/255.0 blue:233/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y0000_Color 
{
	return [UIColor colorWithRed:254/255.0 green:254/255.0 blue:244/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y02_Color 
{
	return [UIColor colorWithRed:246/255.0 green:243/255.0 blue:150/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y04_Color 
{
	return [UIColor colorWithRed:237/255.0 green:229/255.0 blue:86/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y06_Color 
{
	return [UIColor colorWithRed:254/255.0 green:245/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y08_Color 
{
	return [UIColor colorWithRed:254/255.0 green:242/255.0 blue:0/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y11_Color 
{
	return [UIColor colorWithRed:255/255.0 green:251/255.0 blue:204/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y13_Color 
{
	return [UIColor colorWithRed:251/255.0 green:247/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y15_Color 
{
	return [UIColor colorWithRed:254/255.0 green:233/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y17_Color 
{
	return [UIColor colorWithRed:255/255.0 green:228/255.0 blue:85/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y18_Color 
{
	return [UIColor colorWithRed:254/255.0 green:237/255.0 blue:85/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y19_Color 
{
	return [UIColor colorWithRed:255/255.0 green:233/255.0 blue:62/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y21_Color 
{
	return [UIColor colorWithRed:255/255.0 green:238/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y23_Color 
{
	return [UIColor colorWithRed:251/255.0 green:227/255.0 blue:179/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y26_Color 
{
	return [UIColor colorWithRed:240/255.0 green:221/255.0 blue:103/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y28_Color 
{
	return [UIColor colorWithRed:202/255.0 green:168/255.0 blue:105/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y32_Color 
{
	return [UIColor colorWithRed:249/255.0 green:222/255.0 blue:192/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y35_Color 
{
	return [UIColor colorWithRed:255/255.0 green:216/255.0 blue:121/255.0 alpha:255/255.0];
};

+(UIColor *)copic_y38_Color 
{
	return [UIColor colorWithRed:255/255.0 green:210/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg00_Color 
{
	return [UIColor colorWithRed:230/255.0 green:230/255.0 blue:158/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg0000_Color 
{
	return [UIColor colorWithRed:242/255.0 green:247/255.0 blue:224/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg01_Color 
{
	return [UIColor colorWithRed:226/255.0 green:235/255.0 blue:178/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg03_Color 
{
	return [UIColor colorWithRed:222/255.0 green:234/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg05_Color 
{
	return [UIColor colorWithRed:214/255.0 green:229/255.0 blue:146/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg06_Color 
{
	return [UIColor colorWithRed:196/255.0 green:223/255.0 blue:146/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg07_Color 
{
	return [UIColor colorWithRed:165/255.0 green:207/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg09_Color 
{
	return [UIColor colorWithRed:130/255.0 green:197/255.0 blue:102/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg11_Color 
{
	return [UIColor colorWithRed:229/255.0 green:240/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg17_Color 
{
	return [UIColor colorWithRed:114/255.0 green:193/255.0 blue:86/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg21_Color 
{
	return [UIColor colorWithRed:247/255.0 green:246/255.0 blue:190/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg23_Color 
{
	return [UIColor colorWithRed:230/255.0 green:235/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg25_Color 
{
	return [UIColor colorWithRed:208/255.0 green:225/255.0 blue:123/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg41_Color 
{
	return [UIColor colorWithRed:213/255.0 green:235/255.0 blue:212/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg45_Color 
{
	return [UIColor colorWithRed:180/255.0 green:220/255.0 blue:183/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg61_Color 
{
	return [UIColor colorWithRed:214/255.0 green:233/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg63_Color 
{
	return [UIColor colorWithRed:160/255.0 green:202/255.0 blue:162/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg67_Color 
{
	return [UIColor colorWithRed:129/255.0 green:191/255.0 blue:140/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg91_Color 
{
	return [UIColor colorWithRed:218/255.0 green:215/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg93_Color 
{
	return [UIColor colorWithRed:210/255.0 green:210/255.0 blue:156/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg95_Color 
{
	return [UIColor colorWithRed:203/255.0 green:198/255.0 blue:94/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg97_Color 
{
	return [UIColor colorWithRed:149/255.0 green:143/255.0 blue:3/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yg99_Color 
{
	return [UIColor colorWithRed:78/255.0 green:106/255.0 blue:21/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr00_Color 
{
	return [UIColor colorWithRed:254/255.0 green:214/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr0000_Color 
{
	return [UIColor colorWithRed:255/255.0 green:243/255.0 blue:229/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr01_Color 
{
	return [UIColor colorWithRed:254/255.0 green:218/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr02_Color 
{
	return [UIColor colorWithRed:252/255.0 green:220/255.0 blue:197/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr04_Color 
{
	return [UIColor colorWithRed:254/255.0 green:195/255.0 blue:105/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr07_Color 
{
	return [UIColor colorWithRed:242/255.0 green:111/255.0 blue:57/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr09_Color 
{
	return [UIColor colorWithRed:241/255.0 green:85/255.0 blue:36/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr12_Color 
{
	return [UIColor colorWithRed:255/255.0 green:226/255.0 blue:166/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr14_Color 
{
	return [UIColor colorWithRed:254/255.0 green:200/255.0 blue:78/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr15_Color 
{
	return [UIColor colorWithRed:251/255.0 green:184/255.0 blue:132/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr16_Color 
{
	return [UIColor colorWithRed:254/255.0 green:183/255.0 blue:41/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr18_Color 
{
	return [UIColor colorWithRed:242/255.0 green:107/255.0 blue:60/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr20_Color 
{
	return [UIColor colorWithRed:255/255.0 green:225/255.0 blue:191/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr21_Color 
{
	return [UIColor colorWithRed:245/255.0 green:221/255.0 blue:177/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr23_Color 
{
	return [UIColor colorWithRed:236/255.0 green:207/255.0 blue:139/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr24_Color 
{
	return [UIColor colorWithRed:240/255.0 green:207/255.0 blue:100/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr30_Color 
{
	return [UIColor colorWithRed:254/255.0 green:242/255.0 blue:218/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr31_Color 
{
	return [UIColor colorWithRed:255/255.0 green:222/255.0 blue:168/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr61_Color 
{
	return [UIColor colorWithRed:253/255.0 green:218/255.0 blue:196/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr65_Color 
{
	return [UIColor colorWithRed:250/255.0 green:174/255.0 blue:96/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr68_Color 
{
	return [UIColor colorWithRed:243/255.0 green:112/255.0 blue:34/255.0 alpha:255/255.0];
};

+(UIColor *)copic_yr82_Color 
{
	return [UIColor colorWithRed:253/255.0 green:198/255.0 blue:141/255.0 alpha:255/255.0];
};

@end